### PR TITLE
Please review this pull request for Chicken pot pie for dinner recipe! 

### PR DESCRIPTION
**Pull request by lindalee117**
🎯 Objective

_Created dinner recipe
🛠️ Changes made

_Added recipe name, servings, time to prepare, ingredients, equipment needed, steps for preparation, & note! 

👥 Who needs to review this Pull Request?

 @cristinap37 @alchurchy @alyssamzhu   to review this dinner recipe pull request!

### CODE REVIEW

**Comment by alyssamzhu** [comment]
for some reason i don't have editing access to this file so i can't make a commit -- but this dinner recipe looks fantastic

**Review by alyssamzhu — APPROVED** [review]
Chicken pot pie for dinner looks great!

**Comment by lindalee117** [comment]
@joewadcan It doesn't look like any of us in the group have write access to merge these pull requests. Would you help advise?

**Comment by joewadcan** [comment]
@lindalee117 you're totally right, my apologies. You should now have full access to this repo to merge PRs among other things. IF you and your team need more time to complete the assignment, I'm certainly happy to provide it.

**Pull request merged**
